#!/usr/bin/env bash
set -e
echo "Setting up No-Docker mode..."

# Check prerequisites
command -v python3 >/dev/null 2>&1 || { echo "ERROR: python3 required"; exit 1; }
command -v node >/dev/null 2>&1 || { echo "ERROR: node required (for SillyTavern)"; exit 1; }
command -v nginx >/dev/null 2>&1 || { echo "WARNING: nginx not found, install it first"; }

# Install Python deps
pip3 install -r manager/requirements.txt 2>/dev/null || pip install -r manager/requirements.txt

# Init DB and dirs
python3 scripts/init_db.py
mkdir -p users archive backups templates/proxy

# Set runtime_mode
python3 -c "
from manager.db import init_db, get_db
from manager.settings_service import set_settings
init_db()
set_settings({'runtime_mode': 'process'})
print('runtime_mode set to process')
"

# Setup ST release directory (shared across instances)
ST_RELEASE_DIR="${ST_RELEASE_DIR:-$(pwd)/st-release}"
if [ ! -d "$ST_RELEASE_DIR" ]; then
    echo "Cloning SillyTavern release to $ST_RELEASE_DIR ..."
    git clone --depth 1 https://github.com/SillyTavern/SillyTavern.git "$ST_RELEASE_DIR" 2>/dev/null || {
        echo "WARNING: Could not clone ST. Place ST files in $ST_RELEASE_DIR manually."
    }
    if [ -d "$ST_RELEASE_DIR" ]; then
        cd "$ST_RELEASE_DIR" && npm install --omit=dev 2>/dev/null || true
    fi
fi

# Generate nginx base config
NGINX_CONF="${NGINX_CONF_DIR:-/etc/nginx}"
ST_BASE="$(pwd)"
echo "Generating nginx config..."

cat > scripts/st-manager-nginx.conf << NGINXEOF
# ST Cloud Manager — Nginx reverse proxy (Dockerless mode)
# Include this in your nginx.conf http block:
#   include /path/to/st-cloud-manager/scripts/st-manager-nginx.conf;

upstream st_manager {
    server 127.0.0.1:5000;
}

# Manager API + Admin UI
server {
    listen 80;
    server_name ${ST_MANAGER_DOMAIN:-manager.127-0-0-1.sslip.io};

    location / {
        proxy_pass http://st_manager;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}

# Per-instance configs (generated by nginx_config_service.py)
include ${ST_BASE}/nginx-sites/*.conf;
NGINXEOF

mkdir -p nginx-sites

echo ""
echo "================================================"
echo " No-Docker setup complete."
echo ""
echo " Next steps:"
echo "  1. Link nginx config:"
echo "     sudo ln -sf $(pwd)/scripts/st-manager-nginx.conf ${NGINX_CONF}/sites-enabled/st-manager.conf"
echo "     sudo nginx -t && sudo nginx -s reload"
echo ""
echo "  2. Start manager:"
echo "     make start"
echo ""
echo "  3. Set env vars in .env:"
echo "     ST_RUNTIME_MODE=process"
echo "     ST_RELEASE_DIR=$(pwd)/st-release"
echo "     ST_NGINX_CONF_DIR=${NGINX_CONF}"
echo "     ST_NGINX_SITES_SUBDIR=sites-enabled"
echo "================================================"
